const $ = (s) => document.querySelector(s);
const state = { batches: [], batch: null, progress: null };
const statusNames = {draft:'草稿',awaiting_tests:'待试验',testing:'试验中',blocked:'偏差阻断',pending_review:'待复核',frozen:'已冻结',released:'已放行'};
const key = () => crypto.randomUUID();
const payload = (form) => Object.fromEntries(new FormData(form).entries());
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=error?'show error':'show';setTimeout(()=>el.className='',2600)}
async function api(url,options={}){const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message+(data.error?.details?`：${data.error.details.map(x=>x.message).join('；')}`:'')||`请求失败 ${response.status}`);return data}
async function loadBatches(){const f=$('#batch-filter');const q=f?new URLSearchParams(Object.fromEntries(new FormData(f).entries())):new URLSearchParams();for(const [k,v] of [...q])if(!v)q.delete(k);for(const k of ['from','to'])if(q.get(k))q.set(k,new Date(q.get(k)).toISOString());const data=await api('/api/v1/batches?'+q);state.batches=data.batches;renderBatchList()}
function renderBatchList(){$('#batch-list').innerHTML=state.batches.map(b=>{const p=b.progress||{};const risk=p.riskLevel?` · 风险 ${escapeHTML(p.riskLevel)}`:'';return `<button class="batch-item ${state.batch?.id===b.id?'active':''}" data-id="${b.id}"><strong>${escapeHTML(b.venueName)} · ${escapeHTML(b.stageZone)}</strong><span>${statusNames[b.status]} · v${b.version} · 覆盖 ${Number(p.coveragePercent||0).toFixed(0)}% · 未关偏差 ${p.openDeviations||0}${risk}</span></button>`}).join('')||'<p>暂无批次</p>';document.querySelectorAll('.batch-item').forEach(x=>x.onclick=()=>openBatch(x.dataset.id))}
async function openBatch(id){const data=await api(`/api/v1/batches/${id}`);accept(data);$('#empty').hidden=true;$('#detail').hidden=false;renderBatchList()}
function accept(data){state.batch=data.batch;state.progress=data.progress;renderDetail()}
function renderDetail(){const b=state.batch,p=state.progress;$('#status').textContent=statusNames[b.status]||b.status;$('#batch-title').textContent=`${b.venueName} · ${b.stageZone}`;$('#batch-meta').textContent=`演出 ${new Date(b.performanceAt).toLocaleString()} · 负责人 ${b.ownerName} · 版本 ${b.version}`;$('#metric-points').textContent=p.totalPoints;$('#metric-coverage').textContent=`${p.coveragePercent.toFixed(0)}%`;$('#metric-passed').textContent=p.passedPoints;$('#metric-deviations').textContent=p.openDeviations;renderPoints();renderTests();renderDeviations();renderRelease();applyState()}
function renderPoints(){const b=state.batch;$('#points-body').innerHTML=b.points.map(p=>`<tr><td><strong>${escapeHTML(p.pointCode)}</strong></td><td>${escapeHTML(p.hoistSerial)}</td><td>${escapeHTML(p.ropeSpec)}</td><td>${p.ratedLoadKg} / ${p.plannedLoadKg} kg</td><td>${escapeHTML(p.positionNote||'—')}</td></tr>`).join('')||'<tr><td colspan="5">尚未登记吊点</td></tr>';$('#test-point').innerHTML=b.points.map(p=>`<option value="${p.id}">${escapeHTML(p.pointCode)} · ${p.plannedLoadKg}kg</option>`).join('')}
function renderTests(){$('#test-history').innerHTML=[...state.batch.tests].reverse().map(t=>{const p=state.batch.points.find(x=>x.id===t.riggingPointId);return `<article class="record ${t.result==='failed'?'failed':''}"><div><strong>${escapeHTML(p?.pointCode||t.riggingPointId)} · 第 ${t.attemptNo} 次 · ${t.result==='passed'?'合格':'不合格'}</strong><p>目标 ${t.targetLoadKg}kg / 实测 ${t.measuredLoadKg}kg · ${t.holdSeconds}s · 位移 ${t.displacementMm}mm · ${escapeHTML(t.recordedBy)}</p></div></article>`}).join('')||'<p>尚无试验记录</p>'}
function renderDeviations(){$('#deviation-list').innerHTML=state.batch.deviations.map(d=>`<article class="record ${d.status==='closed'?'':'failed'}"><div><strong>${escapeHTML(d.severity)} · ${escapeHTML(d.symptom)} · ${statusText(d.status)}</strong><p>处置：${escapeHTML(d.requiredAction)} · 责任人：${escapeHTML(d.assignee)}${d.assigneeConfirmed?' · 责任已确认':''}${d.remediationEvidence?` · 证据：${escapeHTML(d.remediationEvidence)}`:''}</p></div><div class="record-actions">${d.status!=='closed'&&!d.assigneeConfirmed?`<button data-confirm="${d.id}">确认责任</button>`:''}${d.status!=='closed'&&d.severity!=='critical'?`<button data-upgrade="${d.id}">升级等级</button>`:''}${d.status==='open'?`<input data-evidence="${d.id}" placeholder="整改证据"><button data-remediate="${d.id}">提交证据</button>`:''}${d.status==='remediated'?`<button data-retest="${d.id}">录入关联复测</button>`:''}</div></article>`).join('')||'<p>当前没有偏差</p>';document.querySelectorAll('[data-remediate]').forEach(x=>x.onclick=()=>remediate(x.dataset.remediate));document.querySelectorAll('[data-retest]').forEach(x=>x.onclick=()=>retest(x.dataset.retest));document.querySelectorAll('[data-confirm]').forEach(x=>x.onclick=()=>updateDeviation(x.dataset.confirm,{confirmedBy:prompt('确认人')}));document.querySelectorAll('[data-upgrade]').forEach(x=>x.onclick=()=>updateDeviation(x.dataset.upgrade,{severity:prompt('升级为 major 或 critical')}))}
function renderRelease(){const c=state.batch.credential,r=state.batch.review;$('#credential').innerHTML=c?`<article><small>演出放行凭据</small><h3>No. ${String(c.serialNumber).padStart(6,'0')}</h3><code>${escapeHTML(c.snapshotDigest)}</code><small>${escapeHTML(c.approvedBy)} · ${new Date(c.issuedAt).toLocaleString()} · ${escapeHTML(c.verificationStatus)}</small></article>`:'';$('#review-record').innerHTML=r?`<article class="record"><div><strong>技术复核 · ${escapeHTML(r.approvedBy)}</strong><p>${escapeHTML(r.approvalNote)} · ${r.passedPointCount}/${r.pointCount} 吊点合格 · ${r.closedDeviationCount} 项偏差关闭 · ${new Date(r.reviewedAt).toLocaleString()}</p></div></article>`:''}
function applyState(){const s=state.batch.status;$('#point-form').hidden=s!=='draft';$('#edit-batch').disabled=s!=='draft';$('#lock-list').disabled=s!=='draft'||state.batch.points.length===0;$('#test-form').querySelector('button').disabled=!['awaiting_tests','testing','blocked'].includes(s);$('#approval-form button').disabled=s!=='pending_review';$('#issue-form button').disabled=s!=='frozen'}
async function mutate(path,body,method='POST'){body.expectedVersion=state.batch.version;body.idempotencyKey=key();const data=await api(path,{method,body:JSON.stringify(body)});accept(data);await loadBatches();toast(data.replayed?'已返回此前处理结果':'操作已保存')}
$('#new-batch').onclick=()=>$('#create-dialog').showModal();$('#close-dialog').onclick=()=>$('#create-dialog').close();$('#refresh').onclick=()=>openBatch(state.batch.id);$('#close-edit').onclick=()=>$('#edit-dialog').close();
$('#batch-filter').onsubmit=e=>{e.preventDefault();loadBatches().catch(err=>toast(err.message,true))};
$('#edit-batch').onclick=()=>{const f=$('#edit-form');f.venueName.value=state.batch.venueName;f.stageZone.value=state.batch.stageZone;f.ownerName.value=state.batch.ownerName;const d=new Date(state.batch.performanceAt);f.performanceAt.value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);$('#edit-dialog').showModal()};
$('#edit-form').onsubmit=e=>run(e,async body=>{body.performanceAt=new Date(body.performanceAt).toISOString();await mutate(`/api/v1/batches/${state.batch.id}`,body,'PATCH');$('#edit-dialog').close()});
$('#batch-form').onsubmit=async e=>{e.preventDefault();const body=payload(e.target);body.performanceAt=new Date(body.performanceAt).toISOString();body.expectedVersion=0;body.idempotencyKey=key();try{const data=await api('/api/v1/batches',{method:'POST',body:JSON.stringify(body)});state.batch=data.batch;state.progress=data.progress;$('#create-dialog').close();$('#empty').hidden=true;$('#detail').hidden=false;await loadBatches();renderDetail();toast('批次已创建')}catch(err){toast(err.message,true)}};
$('#point-form').onsubmit=e=>run(e,async body=>{body.ratedLoadKg=+body.ratedLoadKg;body.plannedLoadKg=+body.plannedLoadKg;await mutate(`/api/v1/batches/${state.batch.id}/points`,body);e.target.reset()});
$('#lock-list').onclick=()=>guard(()=>mutate(`/api/v1/batches/${state.batch.id}/lock`,{}));
$('#test-form').onsubmit=e=>run(e,async body=>{['targetLoadKg','measuredLoadKg','displacementMm'].forEach(k=>body[k]=+body[k]);body.holdSeconds=+body.holdSeconds;if(body.symptom||body.requiredAction||body.assignee){body.deviation={severity:body.severity,symptom:body.symptom,requiredAction:body.requiredAction,assignee:body.assignee,confirmedBy:body.confirmedBy,assigneeConfirmed:body.assigneeConfirmed==='on'}}delete body.severity;delete body.symptom;delete body.requiredAction;delete body.assignee;delete body.confirmedBy;delete body.assigneeConfirmed;await mutate(`/api/v1/batches/${state.batch.id}/tests`,body);e.target.reset()});
$('#approval-form').onsubmit=e=>run(e,body=>mutate(`/api/v1/batches/${state.batch.id}/approval`,body));$('#issue-form').onsubmit=e=>run(e,body=>mutate(`/api/v1/batches/${state.batch.id}/credential`,body));
async function remediate(id){const evidence=document.querySelector(`[data-evidence="${id}"]`).value;guard(()=>mutate(`/api/v1/batches/${state.batch.id}/deviations/${id}/remediation`,{evidence}))}
async function retest(id){const target=prompt('目标载荷 kg');if(target===null)return;const measured=prompt('实测载荷 kg');const hold=prompt('保持时长 秒','60');const displacement=prompt('位移 mm','1');const recordedBy=prompt('记录员');guard(()=>mutate(`/api/v1/batches/${state.batch.id}/deviations/${id}/retest`,{targetLoadKg:+target,measuredLoadKg:+measured,holdSeconds:+hold,displacementMm:+displacement,recordedBy}))}
function updateDeviation(id,body){if(!body.confirmedBy&&!body.severity)return;guard(()=>mutate(`/api/v1/batches/${state.batch.id}/deviations/${id}/update`,body))}
$('#verify-current').onclick=()=>guard(async()=>{$('#verify-result').textContent=JSON.stringify(await api(`/api/v1/batches/${state.batch.id}/verification`),null,2)});$('#verify-form').onsubmit=e=>run(e,async body=>{$('#verify-result').textContent=JSON.stringify(await api(`/api/v1/credentials/${body.serial}`),null,2)});
document.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=x.id!==`tab-${btn.dataset.tab}`)});
async function run(event,fn){event.preventDefault();await guard(()=>fn(payload(event.target)))}async function guard(fn){try{await fn()}catch(err){toast(err.message,true)}}function statusText(s){return {open:'待整改',remediated:'待复测',closed:'已关闭'}[s]||s}function escapeHTML(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadBatches().catch(err=>toast(err.message,true));
